security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        api_provider:
            memory:
                users:
                    restapi:  { password: secretpw, roles: [ 'ROLE_API' ] }


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern:  ^/api/.*
            provider: api_provider
            anonymous: ~
            # form_login: false # <- needed or not?
            http_basic:
                realm: "Demo REST API (username: restapi, password: secretpw)"
        main:
            pattern: ^/
            anonymous: ~
            stateless:  true
            http_basic:
                realm: "Demo REST API (username: restapi, password: secretpw)"