AppBundle\Entity\Client:
    type:  entity
    table: AuthClient
    repositoryClass: AppBundle\Entity\ClientRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

